### ISSUE TITLE
please use `cd ~/aws-mlflow-sagemaker-cdk/` liberally in the README instructions

### ISSUE THREAD

**Issue by cfregly** [aws-samples/aws-mlflow-sagemaker-cdk#16]
https://github.com/aws-samples/aws-mlflow-sagemaker-cdk#resizing-the-cloud9
```
./resize-cloud9.sh 100
```
 => 
```
cd ~/aws-mlflow-sagemaker-cdk/
./resize-cloud9.sh 100
```

including beginning tilde as it increases the changes of a successful installation experience.

thanks!

**Comment by ibuchh** [comment]
Fixed.
