### ISSUE TITLE
Cannot import name 'escape' from 'jinja2'

### ISSUE THREAD

**Issue by rddefauw** [aws-samples/aws-mlflow-sagemaker-cdk#23]
In the example notebook, executing the second cell (with the imports) results in this error:

```
cannot import name 'escape' from 'jinja2'
```

I was able to work around it by installing an updated version of Flask:

```
pip install -U Flask==2.1.0
```

I'm not sure if that's the best solution though.

**Comment by pdifranc** [comment]
Hi @rddefauw 
which image are you using in SageMaker Studio? I know there are incompatibilities between the libraries installed in the `Data Science` image (and I reproduced the same error you saw) and the mlflow dependencies. This is the reason the notebook recommends to use a plain `Base Python 2.0` with a `Python 3` kernel. Can you please check whether this solves the issue?

**Comment by rddefauw** [comment]
I was using the Data Science kernel.  I missed the note about the other kernel.  Might be worth a small additional note about the data science kernel since it is the default in Studio?
