### ISSUE TITLE
Access to MLFlow UI 

### ISSUE THREAD

**Issue by DreamyKten** [aws-samples/aws-mlflow-sagemaker-cdk#7]
Hello, 
How to access to MLFlow UI from a on premise computer through AWS Private Link ? 
Thanks

**Comment by pdifranc** [comment]
Hi,

In the end, an AWS PrivateLink is just a Elastic Network Interface card attached to your VPC which network routable on layer 3. The AWS PrivateLink endpoint will get a private IP from your VPC, so you need a private mechanism to reach to it, which can be achieve either via Direct Connect, or more simply via setting a VPN from your on-premise environment. If you want to be able to resolve the DNS name of the endpoint, you can use the features of Route53 like inbound resolvers to provide your onpremise DNS services a mechanism to resolve the AWS PrivateLink endpoint.

Hope this helps.
